// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient(): any {
  const runtimeEnv = typeof process !== 'undefined' ? process.env : undefined;
  const SUPABASE_URL =
    runtimeEnv?.SUPABASE_URL ||
    runtimeEnv?.VITE_SUPABASE_URL ||
    'https://fmcldjrgfbkrthgbyoph.supabase.co';
  const SUPABASE_SERVICE_ROLE_KEY = runtimeEnv?.SUPABASE_SERVICE_ROLE_KEY || runtimeEnv?.VITE_SUPABASE_SERVICE_ROLE_KEY;

  // If required env is present, create a normal admin client.
  if (SUPABASE_URL && SUPABASE_SERVICE_ROLE_KEY) {
    return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      }
    });
  }

  // If env missing, return a proxy object that will throw a clear error when used.
  // This prevents the app from crashing at import time and gives friendlier
  // runtime errors for admin-only operations when running local dev without keys.
  const missing = [
    ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
  ];
  const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Admin operations are disabled.`;
  console.warn(`[Supabase] ${message}`);

  const handler: ProxyHandler<any> = {
    get(_target, prop) {
      return (..._args: any[]) => {
        throw new Error(
          `[Supabase Admin Disabled] ${message} Provide these in your .env to enable admin features (e.g. create users, DB admin). Attempted to call: ${String(prop)}`
        );
      };
    },
    apply(_target, _thisArg, _args) {
      throw new Error(`[Supabase Admin Disabled] ${message}`);
    },
  };

  return new Proxy({}, handler) as unknown as ReturnType<typeof createSupabaseAdminClient>;
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
