// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient(): SupabaseClient<Database> {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const runtimeEnv = typeof process !== 'undefined' ? process.env : undefined;
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    runtimeEnv?.SUPABASE_URL ||
    'https://fmcldjrgfbkrthgbyoph.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    runtimeEnv?.SUPABASE_PUBLISHABLE_KEY ||
    'sb_publishable_CJlt2tKjRddWapjIu47RfA_u0MJZT2l';

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    // Log a warning but do not throw here — return a minimal stub client so the
    // app can render a friendly error or unauthenticated state instead of crashing.
    console.warn(`[Supabase] ${message}`);

    // Minimal stub to satisfy callers on the client-side when env vars are missing.
    // Return deterministic errors instead of undefined methods.
    const buildMissingEnvError = () => new Error(message);
    const stub: any = {
      auth: {
        signInWithPassword: async () => ({ data: { user: null, session: null }, error: buildMissingEnvError() }),
        getSession: async () => ({ data: { session: null } }),
        onAuthStateChange: (_callback: any) => ({ data: { subscription: { unsubscribe: () => {} } } }),
        signOut: async () => ({ error: null }),
      },
    };

    return stub as unknown as ReturnType<typeof createSupabaseClient>;
  }
  

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

